### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by Ir1s666** [zh-lx/code-inspector#127]
> 提示：越详细的信息越有助于排查和解决问题，如果方便请加入本项目 README.md 最下面的 QQ 群或者微信群提供更详细的信息

## Bug 类型

- [x] 安装插件后启动项目编译失败
- [ ] 点击筛选框无法打开 IDE
- [ ] 其他问题

## Bug 描述

_请描述一下你的 bug，最好附上一张报错截图……_
![20240223-115359](https://github.com/zh-lx/code-inspector/assets/122773160/645be131-7eb7-4488-bb69-78852dc1684b)
sudo lsof显示这个:5679没有被使用

## 系统
- [x] mac

## 你使用的打包器及版本

- [x] webpack

## 你使用的 web 框架

- [x] react

**Comment by Ir1s666** [comment]
移除本插件之后编译正常

**Comment by zh-lx** [comment]
使用的插件版本是多少呢

**Comment by Ir1s666** [comment]
0.6.1

**Comment by zh-lx** [comment]
升级到最新的0.9.2版本试试呢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年02月26日 17:59 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zh-lx/code-inspector] 编译失败 (Issue #127) |

0.6.1

**Comment by Ir1s666** [comment]
> 升级到最新的0.9.2版本试试呢
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年02月26日 17:59 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [zh-lx/code-inspector] 编译失败 (Issue #127) | 0.6.1 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

it works。
想了解一下这里是什么原因？为什么会在同一个port去尝试启动服务？

**Comment by zh-lx** [comment]
0.6.1版本有bug，服务缓存启动失败，0.7.0后修复了这个问题



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年02月27日 11:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zh-lx/code-inspector] 编译失败 (Issue #127) |

升级到最新的0.9.2版本试试呢
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2024年02月26日 17:59 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [zh-lx/code-inspector] 编译失败 (Issue #127) | 0.6.1 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***>

it works。
想了解一下这里是什么原因？为什么会在同一个port去尝试启动服务？
