### ISSUE TITLE
不兼容webpack4吗

### ISSUE THREAD

**Issue by jingkeke** [zh-lx/code-inspector#15]
我在一个vue-cli3 的vue2 的老项目里引用了。  用默认的配置直接卡死,就是到50%左右就不动了。

**Comment by zh-lx** [comment]
我这边是兼容了的，有项目地址方便提供我排查一下吗

**Comment by jingkeke** [comment]
@zh-lx   https://github.com/jingkeke/ruoyi-ui/blob/master/package.json. 比如若依这个,我拷贝https://gitee.com/y_project/RuoYi-Vue/tree/master/ruoyi-ui的,加了你的包,  运行` yarn dev `.报错:


```bash
 ERROR  Failed to compile with 1 error                                                            19:50:38

 error  in ./src/components/IconSelect/index.vue?vue&type=template&id=6504d548&scoped=true&

Module Error (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
(Emitted value instead of an instance of Error) 

  Errors compiling template:

  tag <d> has no matching end tag.

  5  |    </el _vc-row="5" _vc-col="7" _vc-path="/Users/jingzy/Downloads/RuoYi-Vue-master/ruoyi-ui/src/components/IconSelect/index.vue" _vc-node="i"-input>
  6  |    <div class="icon-list">
  7  |      <d _vc-row="7" _vc-col="5" _vc-path="/Users/jingzy/Downloads/RuoYi-Vue-master/ruoyi-ui/src/components/IconSelect/index.vue" _vc-node="div"iv v-for="(item, index) in iconList" :key="index" @click="selectedIcon(item)">


```

**Comment by zh-lx** [comment]
感谢，我看一下哈



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月30日 19:59 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [zh-lx/webpack-vue-debug] 不兼容webpack4吗 (Issue #15) |

@zh-lxhttps://github.com/jingkeke/ruoyi-ui/blob/master/package.json. 比如若依这个,我拷贝https://gitee.com/y_project/RuoYi-Vue/tree/master/ruoyi-ui的,加了你的包, 运行yarn dev.报错:

 ERROR  Failed to compile with 1 error                                                            19:50:38



 error  in ./src/components/IconSelect/index.vue?vue&type=template&id=6504d548&scoped=true&



Module Error (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):

(Emitted value instead of an instance of Error) 



  Errors compiling template:



  tag <d> has no matching end tag.



  5  |</el _vc-row="5" _vc-col="7" _vc-path="/Users/jingzy/Downloads/RuoYi-Vue-master/ruoyi-ui/src/components/IconSelect/index.vue" _vc-node="i"-input>

  6  |<div class="icon-list">

  7  |<d _vc-row="7" _vc-col="5" _vc-path="/Users/jingzy/Downloads/RuoYi-Vue-master/ruoyi-ui/src/components/IconSelect/index.vue" _vc-node="div"iv v-for="(item, index) in iconList" :key="index" @click="selectedIcon(item)">

**Comment by jingkeke** [comment]
> 

@zh-lx  我发现我关掉项目重新打开运行了一下,又不报错了...... 我之前测试是一个老项目,vue文件很多超级长的template之类代码.那个是直接卡死了.
