### ISSUE TITLE
Linux下会默认打开vim

### ISSUE THREAD

**Issue by yangxuanx** [zh-lx/code-inspector#62]
Linux下测试，打开了控制台内的vim，vscode已打开。

https://github.com/zh-lx/code-inspector/assets/26968633/cd19971c-83c8-4073-b277-770da83c053f

**Comment by zh-lx** [comment]
系统中存在多个运行中的程序的时候，会按照系统的运行程序的顺序打开第一个，这种情况可以手动指定一下编辑器:

第一种方法，在根目录新建一个 `.env.local` 文件并添加如下内容：
```shell
# 指定 IDE 为 vscode
CODE_EDITOR=code
```


第二种方法：
```js
plugins: [
    CodeInspectorPlugin{
        bundler: 'vite',
        editor: 'code'
    }
]
```

**Comment by yangxuanx** [comment]
手动指定了编辑器还是打开vim

https://github.com/zh-lx/code-inspector/assets/26968633/f12ed69a-c10b-4cf4-90dd-537237f947ca

**Comment by zh-lx** [comment]
好的，我记录下，容我想办法搞个linux环境看一下

**Comment by dinsterizer** [comment]
I am experiencing the same issue on my Ubuntu/Linux.

**Comment by zh-lx** [comment]
@yangxuanx @dinsterizer This issue is caused by the incompatibility of a terminal command I executed on Ubuntu Linux. I have fixed this issue in this [commit](https://github.com/zh-lx/code-inspector/commit/979a20128a0f29adbb44076d1f61d51491f3b8ff).

Now you can install version 0.3.2 to experience it and this version should no longer have this problem. 

Thank you for your feedback！

**Comment by yangxuanx** [comment]
手动指定编辑器可以打开了。

**Comment by zxdmrg** [comment]
![Uploading image.png…]()
我手动指定webstorm后还是会打开pycharm

**Comment by jalcine** [comment]
Ironically, I'd like this to _work_ with Neovim; what would that like look?
